// <auto-generated />
using System;
using Account.Command.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Account.Command.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211217023759_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CQRS.Events.EventModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aggregateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aggregationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("version")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("EventTable");
                });
#pragma warning restore 612, 618
        }
    }
}
